### ISSUE TITLE
Msgpack 1.0.0 save / load test fails

### ISSUE THREAD

**Issue by tgandor** [K3D-tools/chunky3d#2]
This used to work, e.g. with msgpack 0.6.1

```
======================================================================
ERROR: test_save_compress (test_sparse.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "chunky3d/chunky.py", line 1041, in load
    data = msgpack.unpackb(d, object_hook=m.decode, use_list=False)
  File "msgpack/_unpacker.pyx", line 202, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_sparse.py", line 117, in test_save_compress
    self.save_load(6)
  File "test/test_sparse.py", line 97, in save_load
    loaded_s = Sparse.load('save.msgpack')
  File "chunky3d/chunky.py", line 1043, in load
    data = msgpack.unpackb(zlib.decompress(d), object_hook=m.decode, use_list=False)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key

======================================================================
ERROR: test_save_without_compress (test_sparse.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "chunky3d/chunky.py", line 1041, in load
    data = msgpack.unpackb(d, object_hook=m.decode, use_list=False)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test_sparse.py", line 120, in test_save_without_compress
    self.save_load(0)
  File "test/test_sparse.py", line 97, in save_load
    loaded_s = Sparse.load('save.msgpack')
  File "chunky3d/chunky.py", line 1043, in load
    data = msgpack.unpackb(zlib.decompress(d), object_hook=m.decode, use_list=False)
zlib.error: Error -3 while decompressing data: incorrect header check

---------------------------
```

**Comment by artur-trzesiok** [comment]
Problably it's a issue related with msgpack_numpy.  (https://github.com/lebedov/msgpack-numpy/commits/master ). I will study it tomorrow. Maybe we can prepare a PR for msgpack-numpy

**Comment by tgandor** [comment]
No, it turns out it's not `msgpack_numpy`'s fault. Generally, `msgpack` is bad (`use_list`? come on! this is not a transparent serialization format...).

I also don't like the way we deal with compression when loading (`try: ... except: ...`). Any exception gets ignored, and we retry after `unzip`. But this is a topic for another issue (maybe). Right now I'll narrow the exception down.

Finally, there's the `data[b'shape']` - i.e. `raw` option for `unpackb` - which is now `False` by default (and `True` in older `msgpack`). You pack strings as `dict` keys, but unpack bytes (maybe this was all ok in Python 2).

So, the problem can be fixed with some more options when unpacking. Packing, for now, stays as is, because e.g. using `strict_types` would simply make packing impossible.

**Comment by tgandor** [comment]
Tests are now passing (also in the recent(ly added) Travis build).
